version: '2'
services:
  web:
    image: ipepe/kitten
  nginx:
    build: .
    ports:
      - 8080:80
      - 8090:8090
      - 8443:443
    environment:
      - BASIC_AUTH_USERNAME=username
      - BASIC_AUTH_PASSWORD=password
      - PROXY_PASS=http://web/
      - SSL_CERT=/etc/nginx/ssl/nginx.crt
      - SSL_KEY=/etc/nginx/ssl/nginx.key
